
ARCHFLAGS	?= -mmacosx-version-min=10.7 -stdlib=libc++ -arch x86_64 

CXXFLAGS 	+= $(ARCHFLAGS) -DMALLOC_IS_ALIGNED -O3 -ftree-vectorize -I../vamp-plugin-sdk -std=c++11

CFLAGS 		+= $(ARCHFLAGS) -DMALLOC_IS_ALIGNED -O3 -ftree-vectorize

LDFLAGS	    	+= $(ARCHFLAGS)

PLUGIN_LDFLAGS	    	+= $(ARCHFLAGS) -dynamiclib ../vamp-plugin-sdk/libvamp-sdk.a -exported_symbols_list vamp-plugin.list -install_name tipic.dylib

PLUGIN_EXT   := .dylib

MAKEFILE_EXT := .osx

include Makefile.inc


